In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes,load_iris
from sklearn import linear_model,metrics

In [2]:
df1 = load_diabetes()
df = pd.DataFrame(df1.data, columns=df1.feature_names)
df['Target'] = df1.target
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  Target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

In [3]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  Target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [4]:
df.tail()

age       sex       bmi        bp        s1        s2        s3  \
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  Target  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0

In [5]:
df.describe()

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -2.511817e-19  1.230790e-17 -2.245564e-16 -4.797570e-17 -1.381499e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123988e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665608e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670422e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564379e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320436e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean   3.918434e-17 -5.777179e-18 -9.042540e-18  9.293722e-17  1.130318e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260971e-01 -1.377672e-01   
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324559e-02 -3.317903e-02   
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947171e-03 -1.077698e-03   
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243232e-02  2.791705e-02   
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335973e-01  1.356118e-01   

           Target  
count  442.000000  
mean   152.133484  
std     77.093005  
min     25.000000  
25%     87.000000  
50%    140.500000  
75%    211.500000  
max    346.000000

In [6]:
df.isna().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
Target    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['sex'].value_counts()

sex
-0.044642    235
 0.050680    207
Name: count, dtype: int64

In [9]:
df2 = load_iris()
df1 = pd.DataFrame(df2.data , columns=df2.feature_names)
df1['Species']= df2.target
df1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [10]:
a = df2.data
b = np.zeros(150)

In [11]:
for i in range (150):
    b[i]= a[i,1]

In [12]:
b = np.sort(b)

In [13]:
df4 = pd.cut(b ,bins = 3 ,labels=[0,1,2])
print(df4)
a=[]
d=[]
c=[]
for i in range (150):
    if df4[i] == 0:
        a.append(b[i])
    elif df4[i] == 1:
        d.append(b[i])
    else:
        c.append(b[i])
print(a,d,c)
a = pd.DataFrame(a)
d = pd.DataFrame(d)
c = pd.DataFrame(c)
print('Mean of bin1:',a.mean())
print('Mean of bin2:',d.mean())
print('Mean of bin3:',c.mean())

[0, 0, 0, 0, 0, ..., 2, 2, 2, 2, 2]
Length: 150
Categories (3, int64): [0 < 1 < 2]
[np.float64(2.0), np.float64(2.2), np.float64(2.2), np.float64(2.2), np.float64(2.3), np.float64(2.3), np.float64(2.3), np.float64(2.3), np.float64(2.4), np.float64(2.4), np.float64(2.4), np.float64(2.5), np.float64(2.5), np.float64(2.5), np.float64(2.5), np.float64(2.5), np.float64(2.5), np.float64(2.5), np.float64(2.5), np.float64(2.6), np.float64(2.6), np.float64(2.6), np.float64(2.6), np.float64(2.6), np.float64(2.7), np.float64(2.7), np.float64(2.7), np.float64(2.7), np.float64(2.7), np.float64(2.7), np.float64(2.7), np.float64(2.7), np.float64(2.7), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8), np.float64(2.8)] [np.float64(2.9), np.float64(2.9), np.float64(2.9), np.float64(2.9), np.float64(2.9), np.float64(2.9), np.float64(2.9

In [115]:
df4 = pd.cut(b ,bins = 5 )
print(df4)

[(1.998, 2.48], (1.998, 2.48], (1.998, 2.48], (1.998, 2.48], (1.998, 2.48], ..., (3.44, 3.92], (3.92, 4.4], (3.92, 4.4], (3.92, 4.4], (3.92, 4.4]]
Length: 150
Categories (5, interval[float64, right]): [(1.998, 2.48] < (2.48, 2.96] < (2.96, 3.44] < (3.44, 3.92] < (3.92, 4.4]]


In [ ]:
bin1 = np.zeros((30,5))

In [ ]:
for i in range(0,150,5):
    k = int(i/5)
    mean = (b[i] +b[i+1]+b[i+2]+b[i+3]+b[i+4])/5
    for j in range(5):
        bin1[k,j] = mean
print('Bin mean : ',bin1)


Bin mean :  [[2.18 2.18 2.18 2.18 2.18]
 [2.34 2.34 2.34 2.34 2.34]
 [2.48 2.48 2.48 2.48 2.48]
 [2.52 2.52 2.52 2.52 2.52]
 [2.62 2.62 2.62 2.62 2.62]
 [2.7  2.7  2.7  2.7  2.7 ]
 [2.74 2.74 2.74 2.74 2.74]
 [2.8  2.8  2.8  2.8  2.8 ]
 [2.8  2.8  2.8  2.8  2.8 ]
 [2.86 2.86 2.86 2.86 2.86]
 [2.9  2.9  2.9  2.9  2.9 ]
 [2.96 2.96 2.96 2.96 2.96]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.   3.   3.   3.   3.  ]
 [3.04 3.04 3.04 3.04 3.04]
 [3.1  3.1  3.1  3.1  3.1 ]
 [3.12 3.12 3.12 3.12 3.12]
 [3.2  3.2  3.2  3.2  3.2 ]
 [3.2  3.2  3.2  3.2  3.2 ]
 [3.26 3.26 3.26 3.26 3.26]
 [3.34 3.34 3.34 3.34 3.34]
 [3.4  3.4  3.4  3.4  3.4 ]
 [3.4  3.4  3.4  3.4  3.4 ]
 [3.5  3.5  3.5  3.5  3.5 ]
 [3.58 3.58 3.58 3.58 3.58]
 [3.74 3.74 3.74 3.74 3.74]
 [3.82 3.82 3.82 3.82 3.82]
 [4.12 4.12 4.12 4.12 4.12]]


In [19]:
bin2 = np.zeros((30,5))

In [20]:
for i in range(0,150,5):
    k = int(i/5)
    print('k:',k)
    for j in range(5):
        print('b[i]:',b[i])
        print('b[i+j]:',b[i+j])
        if (b[i+j]-b[i])<(b[i+4]-b[i+j]):
            bin2[k,j]=b[i]
        else:
            bin2[k,j]=b[i+4]
print('Bin mean: ',bin2)

k: 0
b[i]: 2.0
b[i+j]: 2.0
b[i]: 2.0
b[i+j]: 2.2
b[i]: 2.0
b[i+j]: 2.2
b[i]: 2.0
b[i+j]: 2.2
b[i]: 2.0
b[i+j]: 2.3
k: 1
b[i]: 2.3
b[i+j]: 2.3
b[i]: 2.3
b[i+j]: 2.3
b[i]: 2.3
b[i+j]: 2.3
b[i]: 2.3
b[i+j]: 2.4
b[i]: 2.3
b[i+j]: 2.4
k: 2
b[i]: 2.4
b[i+j]: 2.4
b[i]: 2.4
b[i+j]: 2.5
b[i]: 2.4
b[i+j]: 2.5
b[i]: 2.4
b[i+j]: 2.5
b[i]: 2.4
b[i+j]: 2.5
k: 3
b[i]: 2.5
b[i+j]: 2.5
b[i]: 2.5
b[i+j]: 2.5
b[i]: 2.5
b[i+j]: 2.5
b[i]: 2.5
b[i+j]: 2.5
b[i]: 2.5
b[i+j]: 2.6
k: 4
b[i]: 2.6
b[i+j]: 2.6
b[i]: 2.6
b[i+j]: 2.6
b[i]: 2.6
b[i+j]: 2.6
b[i]: 2.6
b[i+j]: 2.6
b[i]: 2.6
b[i+j]: 2.7
k: 5
b[i]: 2.7
b[i+j]: 2.7
b[i]: 2.7
b[i+j]: 2.7
b[i]: 2.7
b[i+j]: 2.7
b[i]: 2.7
b[i+j]: 2.7
b[i]: 2.7
b[i+j]: 2.7
k: 6
b[i]: 2.7
b[i+j]: 2.7
b[i]: 2.7
b[i+j]: 2.7
b[i]: 2.7
b[i+j]: 2.7
b[i]: 2.7
b[i+j]: 2.8
b[i]: 2.7
b[i+j]: 2.8
k: 7
b[i]: 2.8
b[i+j]: 2.8
b[i]: 2.8
b[i+j]: 2.8
b[i]: 2.8
b[i+j]: 2.8
b[i]: 2.8
b[i+j]: 2.8
b[i]: 2.8
b[i+j]: 2.8
k: 8
b[i]: 2.8
b[i+j]: 2.8
b[i]: 2.8
b[i+j]: 2.8
b[i]: 2.8
b[i+j]: 2.8
b[i]: 2.8

In [147]:
df4 = pd.cut(b ,bins = 5 )
print(df4)
df5 = pd.IntervalIndex(df4).left
df6 = pd.IntervalIndex(df4).right

[(1.998, 2.48], (1.998, 2.48], (1.998, 2.48], (1.998, 2.48], (1.998, 2.48], ..., (3.44, 3.92], (3.92, 4.4], (3.92, 4.4], (3.92, 4.4], (3.92, 4.4]]
Length: 150
Categories (5, interval[float64, right]): [(1.998, 2.48] < (2.48, 2.96] < (2.96, 3.44] < (3.44, 3.92] < (3.92, 4.4]]


Index([2.48, 2.48, 2.48, 2.48, 2.48, 2.48, 2.48, 2.48, 2.48, 2.48,
       ...
       3.92, 3.92, 3.92, 3.92, 3.92, 3.92,  4.4,  4.4,  4.4,  4.4],
      dtype='float64', length=150)

In [169]:
print(df5.unique())

Index([1.998, 2.48, 2.96, 3.44, 3.92], dtype='float64')


In [187]:
c=[]
mean =[]
for i in df5.unique():
    a=[]
    for j in range (150):
        if df5[j] == i:
            if (b[j] >= df5[j]) & (b[j] < df6[j]) :
                a.append(b[j])
    sum = 0
    i =  0
    for k in a:
        sum = sum + k
        i = i+1
    mean.append(sum/i)


[np.float64(2.272727272727273), np.float64(2.7282608695652186), np.float64(3.151470588235294), np.float64(3.6714285714285717), np.float64(4.1000000000000005)]
